<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <RootNamespace>PhxStudio</RootNamespace>
    <AssemblyName>PhxStudio</AssemblyName>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft\KSoft.csproj">
      <Project>{eb07f515-e27c-4768-8bd8-2829f657807e}</Project>
      <Name>KSoft</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Compression\KSoft.Compression.csproj">
      <Project>{0b27603c-ceb1-4a3a-b56f-cbc14b8c06e7}</Project>
      <Name>KSoft.Compression</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.IO.TagElementStreams\KSoft.IO.TagElementStreams.csproj">
      <Project>{18f32228-8351-4f99-992f-78e9d1ce83d9}</Project>
      <Name>KSoft.IO.TagElementStreams</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Math\KSoft.Math.csproj">
      <Project>{423f13fc-da0c-4c82-b75e-60a1bfea7bb6}</Project>
      <Name>KSoft.Math</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.Security\KSoft.Security.csproj">
      <Project>{0632a00b-de9e-4350-a3f8-3a82f9c780af}</Project>
      <Name>KSoft.Security</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)KSoft\KSoft.WPF\KSoft.WPF.csproj">
      <Project>{8BC67689-8BAA-480E-B2C1-03590AB79259}</Project>
      <Name>KSoft.WPF</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)Games\Wwise\KSoft.Wwise\KSoft.Wwise.csproj">
      <Project>{bddec955-6d39-4058-92e5-f1bf170f860f}</Project>
      <Name>KSoft.Wwise</Name>
    </ProjectReference>
    <ProjectReference Include="$(VitaRootDir)Games\Phoenix\KSoft.Phoenix\KSoft.Phoenix.csproj">
      <Project>{3fd3a05a-4451-49d1-b38e-b897f3444754}</Project>
      <Name>KSoft.Phoenix</Name>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Modules\ProjectExplorer\Images\Folder_Closed16.png" />
    <Resource Include="Modules\ProjectExplorer\Images\Folder_Open16.png" />
    <Resource Include="Modules\TraceList\Images\Start.png" />
    <Resource Include="Modules\TraceList\Images\Resume.png" />
    <Resource Include="Modules\TraceList\Images\Stop.png" />
    <Resource Include="Modules\TraceList\Images\Suspend.png" />
    <Resource Include="Modules\TraceList\Images\Transfer.png" />
    <Resource Include="Modules\TraceList\Images\Error.png" />
    <Resource Include="Modules\TraceList\Images\Information.png" />
    <Resource Include="Modules\TraceList\Images\Verbose.png" />
    <Resource Include="Modules\TraceList\Images\Warning.png" />
    <Resource Include="Modules\TraceList\Images\Critical.png" />
    <Resource Include="Modules\TraceList\Images\Tail.png" />
    <Resource Include="Modules\TraceList\Images\Clear.png" />
    <Resource Include="UI\Images\2015_VSIcon\Activity_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Backward_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Bug_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Cancel_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Cancel_disable_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\ContinuousFolder_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\FileExclude_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\FileGroup_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\FileWarning_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Filter_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Folder_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\FolderOpen_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Forward_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\GoToBottom_color_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Help_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\HistoryTable_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Hourglass_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\InputParameter_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\NewScript_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Open_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\OpenFolder_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\OutputParameter_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Parameter_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Pause_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\PinnedItem_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\ProjectFolderOpen_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Property_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Pushpin_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Pushpin_disabled_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\PushpinUnpin_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\PushpinUnpin_disabled_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Refresh_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Run_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\RunExclude_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Save_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\SaveAll_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Script_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\ScriptGroup_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Search_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Settings_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\SettingsFile_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusAlert_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusBlocked_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusCriticalError_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusHelp_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusInformation_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusInvalid_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusOK_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusPause_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusRun_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusStop_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusUpdate_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\StatusWarning_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Stop_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\TriggeredFolder_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\TriggerScript_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\Uninstall_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\XMLFile_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\ZoomIn_32x.png" />
    <Resource Include="UI\Images\2015_VSIcon\ZoomOut_32x.png" />
    <Resource Include="UI\Images\ImageCatalog\ClearWindowContent.16.16.png" />
  </ItemGroup>
  <ItemGroup>
		<!--5.0.258 is out, but 4.0.210 is what latest Gemini references-->
    <PackageReference Include="Caliburn.Micro" Version="4.0.210" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.129" />
    <!-- <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" /> -->
    <PackageReference Include="GeminiWpf" Version="1.0.76-beta" />
    <PackageReference Include="Gemini.Modules.ErrorList" Version="1.0.76-beta" />
    <PackageReference Include="Gemini.Modules.Inspector" Version="1.0.76-beta" />
    <PackageReference Include="Gemini.Modules.Output" Version="1.0.76-beta" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="System.Waf.Wpf" Version="8.1.0" />
  </ItemGroup>
</Project>
